### ISSUE TITLE
There is the problem when pod accessing its service

### ISSUE THREAD

**Issue by duyanghao** [FabEdge/fabedge#169]
**Describe the bug**
When using fabedge on superedge, there is a problem when pod accessing its service.

**To Reproduce**
1. Create echo-service deployment and service on superedge.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - echo
              topologyKey: "kubernetes.io/hostname"
      containers:
      - image: superedge/echoserver:2.2
        name: echo
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: echo-service
  namespace: default
spec:
  selector:
    app: echo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
```

2. Exec into one echo-service pod and access echo-service. 
3. There appears intermittent problems when access echo-service.

**Expected behavior**
Pod normally access its service.
